#!/usr/bin/env bash
# scripts/regenerate-docs.sh — manual regen of cross-cutting docs from adapter
# metadata. Intended to be run by hand; never by hooks. Drift is caught by
# tests/lint.sh (Task 13). See: extension-model spec §6.

set -euo pipefail
IFS=$'\n\t'

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB_TOOL_DIR="${REPO_ROOT}/scripts/lib/tool"

emit_tool_versions() {
  local to_stdout="${1:-}"
  local out_file="${REPO_ROOT}/references/tool-versions.md"
  local body
  body="$(
    printf '# Tool versions (autogenerated — do not edit; run scripts/regenerate-docs.sh)\n\n'
    printf '| Tool | Version pin | Install hint | Cheatsheet |\n'
    printf '|---|---|---|---|\n'
    shopt -s nullglob
    for adapter_file in "${LIB_TOOL_DIR}"/*.sh; do
      [ "$(basename "${adapter_file}")" = ".gitkeep" ] && continue
      meta="$(source "${adapter_file}" 2>/dev/null; tool_metadata 2>/dev/null)"
      doctor="$(source "${adapter_file}" 2>/dev/null; tool_doctor_check 2>/dev/null)"
      jq -nr --argjson meta "${meta}" --argjson doctor "${doctor}" \
        '"| \($meta.name) | \($meta.version_pin) | \($doctor.install_hint // "n/a") | [\($meta.cheatsheet_path)](../\($meta.cheatsheet_path)) |"'
    done
    shopt -u nullglob
  )"
  if [ "${to_stdout}" = "--to-stdout" ]; then
    printf '%s\n' "${body}"
  else
    printf '%s\n' "${body}" > "${out_file}"
  fi
}

emit_skill_md() {
  local to_stdout="${1:-}"
  local skill_md="${REPO_ROOT}/SKILL.md"
  local body
  body="$(
    printf '<!-- BEGIN AUTOGEN: tools-table — generated by scripts/regenerate-docs.sh -->\n'
    printf '| Tool | Strengths | Cheatsheet |\n'
    printf '|---|---|---|\n'
    shopt -s nullglob
    for adapter_file in "${LIB_TOOL_DIR}"/*.sh; do
      [ "$(basename "${adapter_file}")" = ".gitkeep" ] && continue
      meta="$(source "${adapter_file}" 2>/dev/null; tool_metadata 2>/dev/null)"
      caps="$(source "${adapter_file}" 2>/dev/null; tool_capabilities 2>/dev/null)"
      verb_count="$(jq -r '.verbs | length' <<<"${caps}")"
      jq -nr --argjson meta "${meta}" --argjson n "${verb_count}" \
        '"| \($meta.name) | declares \($n) verbs | [\($meta.cheatsheet_path)](\($meta.cheatsheet_path)) |"'
    done
    shopt -u nullglob
    printf '<!-- END AUTOGEN: tools-table -->\n'
  )"
  if [ "${to_stdout}" = "--to-stdout" ]; then
    printf '%s' "${body}"
    return
  fi
  local tmp body_file
  tmp="$(mktemp)"
  body_file="$(mktemp)"
  printf '%s' "${body}" > "${body_file}"
  awk -v body_file="${body_file}" '
    /<!-- BEGIN AUTOGEN: tools-table/ {
      while ((getline line < body_file) > 0) print line
      close(body_file)
      in_block=1
      next
    }
    /<!-- END AUTOGEN: tools-table -->/ { in_block=0; next }
    !in_block { print }
  ' "${skill_md}" > "${tmp}"
  mv "${tmp}" "${skill_md}"
  rm -f "${body_file}"
}

case "${1:-}" in
  --to-stdout)
    case "${2:-}" in
      tool-versions) emit_tool_versions --to-stdout ;;
      skill-md)      emit_skill_md --to-stdout ;;
      *) printf 'usage: %s --to-stdout {tool-versions|skill-md}\n' "$0" >&2; exit 2 ;;
    esac
    ;;
  tool-versions) emit_tool_versions ;;
  skill-md)      emit_skill_md ;;
  ""|all)
    emit_tool_versions
    emit_skill_md
    ;;
  *)
    printf 'usage: %s [tool-versions|skill-md|all|--to-stdout {tool-versions|skill-md}]\n' "$0" >&2
    exit 2
    ;;
esac
